language: swift
osx_image: xcode10.1

matrix:
  include:
    - xcode_scheme: Gzip macOS
      xcode_sdk: macosx
      xcode_destination: platform=macOS
    - xcode_scheme: Gzip iOS
      xcode_sdk: iphonesimulator
      xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X

script:
  - swiftlint
  - swift test
  - xcodebuild
      -scheme "$TRAVIS_XCODE_SCHEME"
      -sdk "$TRAVIS_XCODE_SDK"
      -destination "$DESTINATION"
      clean test
      | xcpretty -f `xcpretty-travis-formatter`
  - pod lib lint --quick
after_success:
  - bash <(curl -s https://codecov.io/bash)
