language: objective-c
osx_image: xcode8.2

xcode_project: Gzip.xcodeproj
matrix:
  include:
    - xcode_scheme: Gzip macOS
      xcode_sdk: macosx
      env: DESTINATION="arch=x86_64"
    - xcode_scheme: Gzip iOS
      xcode_sdk: iphonesimulator
      env: DESTINATION="OS=10.0,name=iPhone SE"

before_install:
  - gem install xcpretty
  - gem install xcpretty-travis-formatter
  - gem install cocoapods
script:
  - swiftlint
  - xcodebuild
      -project "$TRAVIS_XCODE_PROJECT"
      -scheme "$TRAVIS_XCODE_SCHEME"
      -sdk "$TRAVIS_XCODE_SDK"
      -destination "$DESTINATION"
      clean test
      | xcpretty -f `xcpretty-travis-formatter`
  - pod lib lint --quick
after_success:
  - bash <(curl -s https://codecov.io/bash)
